name: Our First Workflow
on: push
jobs:
  echo:
    runs-on: [self-hosted, linux]
    steps:
      - run: ls -al /var/log/
  pwd-ls:
    name: PWD & LS
    runs-on: git-action
    steps:
      - name: Print working directory
        run: pwd
      - name: network interface
        run: ifconfig -a
