name: Our First Workflow
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hi"
  pwd-ls:
    name: PWD & LS
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory
        run: pwd && la -alh
      - name: network interface
        run: ifconfig -a
